using System.Text;
using ArchitectLuna.Core.Generation;

namespace ArchitectLuna.Cli.Scaffolding;

/// <summary>
/// Builds the Api project's Program.cs in the required "clean startup" shape (see
/// docs/requirements/001-implementation-architecture.md §Generated Startup Style): logging, three
/// AddX calls, middleware, endpoint mapping — nothing else. Every registration detail lives
/// behind the extension methods generated by <see cref="FoundationFiles"/>, so Program.cs is
/// never regenerated when features are added.
///
/// One deliberate deviation per adapter: Wolverine's handler discovery is an IHostBuilder
/// concern (`UseWolverine`), so Wolverine solutions carry one extra `builder.Host.UseWolverine`
/// line — the adapter seam is allowed to change framework-specific setup, never the HTTP surface.
/// </summary>
public static class ProgramCsBuilder
{
    public static string BuildProgramCs(GenerationContext context, string adapterName)
    {
        var usings = new List<string>
        {
            context.Api.RootNamespace,
            $"{context.Api.RootNamespace}.Common",
            context.Application.RootNamespace,
            context.Infrastructure.RootNamespace,
        };

        var wolverineHostLines = new List<string>();
        if (adapterName == "wolverine")
        {
            usings.Add("Wolverine");
            wolverineHostLines.Add("builder.Host.UseWolverine(opts =>");
            wolverineHostLines.Add("{");
            // WolverineFx core no longer ships the runtime compiler; without this the app throws
            // at startup (TypeLoadMode.Dynamic with no IAssemblyGenerator registered).
            wolverineHostLines.Add("    opts.UseRuntimeCompilation();");
            if (context.HasSeparateInfrastructure)
            {
                // Handlers live in the Application assembly, not the Api assembly Wolverine scans
                // by default; ApplicationDependencyInjection doubles as the assembly anchor type.
                wolverineHostLines.Add("    opts.Discovery.IncludeAssembly(typeof(ApplicationDependencyInjection).Assembly);");
            }

            wolverineHostLines.Add("});");
        }
        else if (adapterName != "mediatr")
        {
            throw new InvalidOperationException($"Unknown adapter '{adapterName}'.");
        }

        var sb = new StringBuilder();
        foreach (var u in usings.Distinct())
        {
            sb.AppendLine($"using {u};");
        }

        sb.AppendLine();
        sb.AppendLine("var builder = WebApplication.CreateBuilder(args);");
        sb.AppendLine();
        sb.AppendLine("builder.Host.UseApiLogging(builder.Configuration);");
        if (wolverineHostLines.Count > 0)
        {
            sb.AppendLine();
            foreach (var line in wolverineHostLines)
            {
                sb.AppendLine(line);
            }
        }

        sb.AppendLine();
        sb.AppendLine("builder.Services");
        sb.AppendLine("    .AddApi(builder.Configuration)");
        sb.AppendLine("    .AddApplication()");
        sb.AppendLine("    .AddInfrastructure(builder.Configuration);");
        sb.AppendLine();
        sb.AppendLine("var app = builder.Build();");
        sb.AppendLine();
        sb.AppendLine("app.UseApiMiddleware();");
        sb.AppendLine("app.MapApiEndpoints();");
        sb.AppendLine();
        sb.AppendLine("app.Run();");
        sb.AppendLine();
        sb.AppendLine("// Exposed for WebApplicationFactory<Program> in the Api test project.");
        sb.Append("public partial class Program { }");
        return sb.ToString();
    }
}
